language: java
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y ubuntu-desktop
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
env: DISPLAY=:99
sudo: false
script: 
- 'mvn clean verify'
- 'if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]]; then mvn sonar:sonar -Dsonar.login=${SONAR_TOKEN}; fi'
jdk:
- oraclejdk8
addons:
  sonarcloud:
    organization: "lhein-github"
    branches:
      - master
cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
  - $HOME/.gradle/
deploy:
  provider: releases
  api_key:  ${DEPLOY_TOKEN}
  file: "server/target/camel-lsp-server-1.0.0-SNAPSHOT.jar"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
  branches:
    only:
      - master
