language: java
sudo: false
script: 
- 'mvn clean verify'
- 'if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]]; then mvn sonar:sonar -Dsonar.login=${SONAR_TOKEN}; fi'
jdk:
- oraclejdk8
addons:
  sonarcloud:
#    organization: "default"
    token:
      secure: 305b710aa5901c856919aec4a16c9e5334cc2766
    branches:
      - master
cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
  - $HOME/.gradle/
#deploy:
#  provider: releases
#  api_key:
#    secure: YOUR_API_KEY_ENCRYPTED
#  file: "FILE TO UPLOAD"
#  skip_cleanup: true
#  on:
#    tags: true
#  branches:
#    only:
#      - master
