language: java
before_install:
- "dbus-uuidgen > /var/lib/dbus/machine-id"
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
env: DISPLAY=:99
sudo: false
script: 
- 'mvn clean verify'
- 'if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]]; then mvn sonar:sonar -Dsonar.login=${SONAR_TOKEN}; fi'
jdk:
- oraclejdk8
addons:
  sonarcloud:
    organization: "lhein-github"
    branches:
      - master
cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
  - $HOME/.gradle/
#deploy:
#  provider: releases
#  api_key:
#    secure: YOUR_API_KEY_ENCRYPTED
#  file: "FILE TO UPLOAD"
#  skip_cleanup: true
#  on:
#    tags: true
#  branches:
#    only:
#      - master
